SellySafe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sellysafeweb.urls')),
]

sellysafeweb/urls.py
from django.conf.urls import url

from sellysafeweb import views

app_name = 'sellysafeweb'

urlpatterns = [

    # About page view
    url(r'about', views.about, name='about'),

    # Main map view
    url(r'map', views.map, name='map'),

    # Feedback Confirmation view once feedback page recieves a valid response
    url(r'feedback_confirmation', views.feedback_confirmation, name='feedback_confirmation'),

    # Page to submit feedback
    url(r'feedback', views.feedback, name='feedback'),

    # Blank URL redirect
    url('', views.redirect_to_map, name='redirect_to_map')
]

sellysafeweb/models.py
from django.db import models
from django.utils import timezone

# Model to hold report location, contents and datetime
class Report(models.Model):
    contents = models.TextField(max_length=200, default="")
    lat = models.FloatField()
    long = models.FloatField()
    datetime = models.DateTimeField(default=timezone.now)


# Model to hold app feedback
class Feedback(models.Model):
    contents = models.TextField(max_length=1000, default="")
    email = models.CharField(max_length=50)

sellysafeweb/forms.py
from django import forms
from django.core.exceptions import ValidationError

from SellySafe import settings
from .models import Report, Feedback

# Custom Datetime Widget to use HTML5 Datetime picker
class DateTimeInput(forms.DateInput):
    input_type = 'datetime-local'

    def __init__(self, **kwargs):
        # Use datetime format from Django Settings
        kwargs["format"] = settings.DATETIME_INPUT_FORMATS[0]

        super().__init__(**kwargs)


# Report form to add a new report
class ReportForm(forms.Form):

    # Choices for datetime options
    CHOICES = [(0, 'Just now'),
               (5, '5 minutes ago'),
               (15, '15 minutes ago'),
               (30, '30 minutes ago'),
               (1, '1 hour ago'),
               (2, '2 hours ago'),
               (3, '3 hours ago'),
               (4, '4 hours ago')]

    datetime = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect, label="When did this happen?",
                                 required=True, initial=0)

    # Define hidden inputs not shown to the user. Lat and Long are set through JS when a user clicks on the map.
    lat = forms.FloatField(widget=forms.HiddenInput)
    long = forms.FloatField(widget=forms.HiddenInput)

    contents = forms.CharField(widget=forms.TextInput, label="Please describe what happened", required=True)

    # Clean data on a submitted form
    def clean(self):
        cd = self.cleaned_data

        bounds = settings.BOUNDS
        bl = bounds[0]
        tr = bounds[1]

        # Check if submitted Lat / Long is within defined map bounds. (To prevent malicious post form requests)
        if cd['long'] > tr[0] or cd['long'] < bl[0]:
            raise ValidationError("Longitude out of bounds")
        if cd['lat'] > tr[1] or cd['lat'] < bl[1]:
            raise ValidationError("Latitude out of bounds")

    class Meta:
        model = Report
        fields = ("contents", "lat", "long", "datetime")


# Feedback form for users to submit feedback
class FeedbackForm(forms.ModelForm):
    contents = forms.CharField(required=True, label="Please enter your feedback below")
    email = forms.CharField(required=False, label="Email (Optional), to allow us to get in touch")

    class Meta:
        model = Feedback
        fields = ("contents", "email")

sellysafeweb/views.py
import datetime as dt

from django.shortcuts import render, redirect

from SellySafe import settings
from sellysafeweb.forms import ReportForm, FeedbackForm
from sellysafeweb.models import Report

# Redirect for empty sub-domain to /map
def redirect_to_map(request):
    return redirect('sellysafeweb:map')


# Main map view
def map(request):

    # Assign the submitted form or create one if it doesn't exist
    form = ReportForm(request.POST or None)

    # If user submits the form
    if request.method == 'POST':
        if form.is_valid():

            # Integer representing form choices ['just now', '5 minutes ago', ...] etc
            date_choice = form.cleaned_data['datetime']

            # Assign the corresponding time offsets from the current time
            if int(date_choice) > 4:
                datetime = dt.datetime.now() - dt.timedelta(minutes=int(date_choice))
            else:
                datetime = dt.datetime.now() - dt.timedelta(hours=int(date_choice))

            # Account for BST times
            datetime += dt.timedelta(hours = settings.BST_OFFSET)

            # Create a report object from the form data
            report = Report.objects.create(contents=form.cleaned_data['contents'],
                                           lat=form.cleaned_data['lat'],
                                           long=form.cleaned_data['long'],
                                           datetime=datetime)

            # Save the form to the database
            report.save()
            return redirect('sellysafeweb:map')

    # Filter the reports by n days ago. +1 needed as date duration is inclusive.
    cutoff_date = dt.date.today() - dt.timedelta(days=settings.SHOW_DURATION + 1)
    reports = Report.objects.filter(datetime__gte=cutoff_date)

    # Render the HTML file with the following parameters
    return render(request, 'sellysafeweb/map.html', {
        'reports': reports,
        'form': form,
        'map_box_key': settings.MAPBOX_KEY,
        'city_center': settings.CITY_CENTER,
        'bounds': settings.BOUNDS,
        'duration': settings.SHOW_DURATION,
    })


# About page rendering
def about(request):
    return render(request, 'sellysafeweb/about.html')


# Render an HTML feedback form view and handle form generating and posting
def feedback(request):
    form = FeedbackForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save(commit=True)
            return redirect('sellysafeweb:feedback_confirmation')
    return render(request, 'sellysafeweb/feedback.html', {'form': form})


# Render a confirmation that the form submission was successful
def feedback_confirmation(request):
    return render(request, 'sellysafeweb/feedback_confirmation.html')

sellysafeweb/templates/sellysafeweb/about.html
{% extends 'sellysafeweb/base.html' %}
{% block title %}About{% endblock %}
{% block head_scripts %}
    <!--Loading static content-->
    {% load static %}

{% endblock %}

{% block content %}
    {% include 'sellysafeweb/navbar.html' %}


    <div class="container">
        <h3 class="header">About</h3>
        <p class="flow-text">SellySafe aims to let UOB students view reports of incidents occurring around Selly Oak. Is
            someone walking through your garden? Is someone trying to open doors on your street? Report it on the map
            and let others know where and when it happened, allowing them to take necessary precautions
            with regards to the incident. This site gives you an interactive map, letting you see
            recent incidents near you.</p>
        <img alt="anim" src="{% static 'sellysafeweb/media/anim.gif' %}" width="100%" height="auto">
    </div>

    <div class="parallax-container center valign-wrapper">
        <div class="container">
            <a class="waves-effect btn-large deep-orange hoverable" href={% url 'sellysafeweb:map' %}><i
                    class="material-icons right">map</i>Go To The Map</a>
        </div>

        <div class="parallax">
            <img src= {% static 'sellysafeweb/media/mapimg.jpg' %}>
        </div>
    </div>

    <div class="container">
        <h3 class="header">Why</h3>
        <p class="flow-text">This was created as a lockdown project to help people stay safe in and around Selly Oak.
            I aim to help improve safety for students living in post first year accommodation. Furthermore, I aim to
            give
            first year students an indication of the safer areas to live in 2nd year, as well as where to avoid when
            going out.
        </p>
        <h3 class="header">Disclaimer</h3>
        <p class="flow-text">While I hope this map helps people during their time in Selly Oak, this is not intended
            to be a replacement for the <a class="deep-orange-text"
                                           href="https://www.police.uk/pu/your-area/west-midlands-police/selly-oak/?tab=CrimeMap"
                                           target="blank">
                Official Police Crime Map</a> for Selly Oak, which contains recent reported incidents and the police
            investigation
            status for each incident.</p>
    </div>

    <footer class="page-footer grey darken-4">
        <footer class="footer-copyright">
            <div class="container center">
                <a href="https://github.com/danielbatchford" class="white-text" target="blank">Created by Daniel
                    Batchford -
                    2020</a>
            </div>
        </footer>
    </footer>
{% endblock %}

sellysafeweb/templates/sellysafeweb/add_header_info.html
<div class="container" id="addReportHeader" style="display: none">
    <div class="card animate__animated animate__slideInDown">
        <div class="card-content center">Please select the report location on the map</div>
    </div>

</div>

sellysafeweb/templates/sellysafeweb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta property="og:image" content="{% static 'sellysafeweb/media/mapimg.jpg' %}"/>
    <title>SellySafe - {% block title %}{% endblock %}</title>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Import materialize.css-->
    <link
            type="text/css"
            rel="stylesheet"
            href="{% static 'sellysafeweb/css/materialize.css' %}"
            media="screen,projection"
    >

    <!-- Animate CSS ref -->
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"
    />

    <!-- Import own styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'sellysafeweb/css/style.css' %}">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--JS Files-->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'sellysafeweb/js/materialize.js' %}"></script>


    <!--Favicon-->
    <link rel="icon" href={% static 'sellysafeweb/media/favicon.ico' %}>
    {% block head_scripts %}
    {% endblock %}

</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

sellysafeweb/templates/sellysafeweb/fab_btns.html
<div class="fixed-action-btn">
    <a class="btn-floating btn-large deep-orange animate__animated animate__slideInRight hoverable">
        <i class="large material-icons">reorder</i>
    </a>
    <ul>
        <li><a class="btn-floating white hoverable" onclick="toggleAddMode()"><i class="material-icons black-text"
                                                                                 id="addButton">add</i></a>
        <li><a class="btn-floating white hoverable" href= {% url 'sellysafeweb:about' %}><i
                class="material-icons black-text">help</i></a>
        </li>
        <li><a class="btn-floating white hoverable"><i class="material-icons black-text" onclick=toggleTheme()>visibility</i></a>
        </li>
    </ul>
</div>

sellysafeweb/templates/sellysafeweb/feedback.html
{% extends 'sellysafeweb/base.html' %}
{% block title %}Feedback{% endblock %}
{% block head_scripts %}{% endblock %}

{% block content %}
    {% include 'sellysafeweb/navbar.html' %}

    <div class="container">
        <div class="card">

            <form action={% url 'sellysafeweb:feedback' %} method="POST" class="from-group">

                <div class="card-content">
                    <div class="card-title">
                        <h4>Submit Feedback</h4>
                    </div>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button
                            id="feedback_button"
                            type="submit"
                            class="btn-flat deep-orange-text"
                    >Send Feedback
                    </button>
                </div>

            </form>
        </div>
    </div>
{% endblock %}

sellysafeweb/templates/sellysafeweb/feedback_confirmation.html
{% extends 'sellysafeweb/base.html' %}
{% block title %}Thanks!{% endblock %}
{% block head_scripts %}{% endblock %}
{% block content %}
    {% include 'sellysafeweb/navbar.html' %}
    <br>
    <div class="container center">
        <h2>Thanks!</h2>
        <a class="btn-large deep-orange waves-effect" href="{% url 'sellysafeweb:map' %}">Return to the map</a>
    </div>
{% endblock %}

sellysafeweb/templates/sellysafeweb/floating_logo.html
<br>
<div class="row">
    {% load static %}
    <div class="left-align card col s4 m3 l2 xl2 animate__animated animate__slideInLeft" id="floating_logo">
        <div class="card-content">
            <div class="center">
                <span> <img alt="logoOrange" src="{% static 'sellysafeweb/media/longlogoorangetrn.png' %}" width="100px"
                            height="auto"></span>
            </div>
            <p>Showing reports from the last {{ duration }} days.</p>
        </div>
    </div>
</div>

sellysafeweb/templates/sellysafeweb/map.html
{% extends 'sellysafeweb/base.html' %}
{% block title %}Map View{% endblock %}

{% block head_scripts %}
    <!--MapBox Reference-->
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.11.0/mapbox-gl.css' rel='stylesheet'/>
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.11.0/mapbox-gl.js'></script>
{% endblock %}

{% block content %}

    <div id='map'></div>
    {% include 'sellysafeweb/map_scripts.html' %}
    {% include 'sellysafeweb/ui_scripts.html' %}
    {% include 'sellysafeweb/fab_btns.html' %}
    {% include 'sellysafeweb/report_modal.html' %}
    {% include 'sellysafeweb/add_header_info.html' %}
    {% include 'sellysafeweb/floating_logo.html' %}
{% endblock %}

sellysafeweb/templates/sellysafeweb/map_scripts.html
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.fixed-action-btn');
        var instances = M.FloatingActionButton.init(elems, {
            direction: 'up',
            hoverEnabled: false,
        });
    });

    var themeURL = localStorage.getItem('themeURL')
    if (themeURL == null) {
        themeURL = 'mapbox://styles/mapbox/light-v10?optimize=true';
        localStorage.setItem('themeURL', themeURL);
    }

    var addMarker = new mapboxgl.Marker();

    mapboxgl.accessToken = '{{ map_box_key }}';
    var map = new mapboxgl.Map({
        container: 'map',
        style: themeURL,
        zoom: 15,
        maxZoom: 18,
        minZoom: 14,
        maxPitch: 0,
        pitchWithRotate: false,
        touchPitch: false,
        logoPosition: 'bottom-left',
        center: {{city_center}},
        maxBounds: {{ bounds|safe }},

    });
    // disable map rotation using right click + drag
    map.dragRotate.disable();

    // disable map rotation using touch rotation gesture
    map.touchZoomRotate.disableRotation();


    function toggleTheme() {

        if (themeURL === 'mapbox://styles/mapbox/dark-v10?optimize=true') {
            themeURL = 'mapbox://styles/mapbox/light-v10?optimize=true';
        } else themeURL = 'mapbox://styles/mapbox/dark-v10?optimize=true';

        map.setStyle(themeURL);
        localStorage.setItem('themeURL', themeURL);
    }

    {% for report in reports %}

        // Create a popup
        var popup = new mapboxgl.Popup({
            offset: 25,
            closeButton: false,
            closeOnClick: true,
        })

        popup.setHTML("<p>{{ report.datetime }}</p><p style='word-wrap: break-word;'>{{ report.contents }}</p>");

        // create marker with above popup
        var marker = new mapboxgl.Marker()
            .setPopup(popup)
            .setLngLat([{{report.long}}, {{ report.lat}}])
            .addTo(map);

    {% endfor %}

    map.on('click', function (e) {
        if (!addMode) return;
        // Get Lat Long cords of click
        var clickLongLat = e.lngLat.wrap();

        //add a marker at these co-ordinates. Reference addMarker is preserved
        addMarker.setLngLat([clickLongLat['lng'], clickLongLat['lat']]).addTo(map);

        // Update hidden form values with lat long from function
        $('#id_lat').val(clickLongLat['lat']);
        $('#id_long').val(clickLongLat['lng']);

        // Open materialise modal
        $('#addReportModal').modal('open');

        document.getElementById('addReportHeader').style.display = "none";

        map.flyTo({

            center: [clickLongLat['lng'], clickLongLat['lat']],
            zoom: 18,
            speed: 1,
            curve: 1,
            essential: true
        });
    })

    function flyToCenter() {
        map.flyTo({

            center: {{ city_center }},
            zoom: 16,
            speed: 1,
            curve: 1,
            essential: true
        });
    }


</script>

sellysafeweb/templates/sellysafeweb/navbar.html
<!--Init SideNav for mobile and tooltips-->
<script>
    $(document).ready(function () {
        $('.parallax').parallax();
        $('.sidenav').sidenav();
        $('.tooltipped').tooltip();

    });

    {% load static %}
</script>


<nav class="grey darken-4" role="navigation">
    <div class="nav-wrapper">
        <a href="{% url 'sellysafeweb:map' %}" class="brand-logo center">
            <img alt="logo" src="{% static 'sellysafeweb/media/logolongtrn.png' %}" width='auto' height="50px"
                 style="vertical-align: middle">
        </a>

        <ul class="right hide-on-med-and-down">
            <li><a class="waves-effect tooltipped" data-position="bottom"
                   data-tooltip="Submit some feedback"
                   href="{% url 'sellysafeweb:feedback' %}">Feedback</a></li>
            <li><a class="waves-effect tooltipped" data-position="bottom"
                   data-tooltip="Help me keep the paid servers running!"
                   href="https://buymeacoff.ee/danielbatchford" target="blank">Donate</a></li>
        </ul>

        <ul id="nav-mobile" class="sidenav grey darken-4">
            <li><a class="waves-effect white-text" href="https://buymeacoff.ee/danielbatchford"
                   target="blank">Donate</a>
            <li><a class="waves-effect white-text" href="{% url 'sellysafeweb:feedback' %}">Feedback</a>
            </li>
        </ul>
        <a data-target="nav-mobile" class="sidenav-trigger waves-effect">
            <i class="material-icons">menu</i></a>
    </div>
</nav>

sellysafeweb/templates/sellysafeweb/report_modal.html
<div id="addReportModal" class="modal class modal bottom-sheet modal-fixed-footer">
    {% load material_form %}
    <form action={% url 'sellysafeweb:map' %} method="POST" class="from-group">
        <div class="modal-content">

            <h4>Add A Report</h4>


            {% csrf_token %}
            {% form form=form %}{% endform %}
        </div>
        <div class="modal-footer">
            <div class="right">
                <button
                        id="submit_button"
                        type="submit"
                        class="btn-flat deep-orange-text"
                >

                    Add This Report
                    <i class="material-icons right">send</i>
                </button>
            </div>
        </div>
    </form>
</div>

sellysafeweb/templates/sellysafeweb/ui_scripts.html
<script> $(document).ready(function () {

    $('.modal').modal(
        {
            inDuration: 500,
            outDuration: 500,
            opacity: 0,
            onCloseStart: () => {

                addMarker.remove();
                document.getElementById('addReportHeader').style.display = "block";
                flyToCenter();
            },
        }
    );
});

var addMode = false;

function toggleAddMode() {
    addMode = !addMode;
    header = document.getElementById('addReportHeader');
    button = document.getElementById('addButton');
    logo = document.getElementById('floating_logo');
    if (addMode) {
        header.style.display = "block";
        button.innerHTML = "clear";
        logo.style.display = "none";
        flyToCenter();
    } else {
        header.style.display = "none";
        button.innerHTML = "add";
        logo.style.display = "block";

    }
}


</script>